services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\LocationPosts\ConditionalOnModule\Tags\FieldResolvers\:
        resource: '../../../src/ConditionalOnModule/Tags/FieldResolvers/*'
