services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPCMSSchema\LocationPosts\TypeAPIs\LocationPostTypeAPIInterface:
        class: \PoPCMSSchema\LocationPostsWP\TypeAPIs\LocationPostTypeAPI
